usage: hisat2_read_statistics.py [-h] [-n READ_COUNT] [read_file]
hisat2_read_statistics.py: error: unrecognized arguments: ../data/raw/M-C-216_R1_001.fastq.gz ../data/raw/M-C-218_R1_001.fastq.gz ../data/raw/M-C-226_R1_001.fastq.gz ../data/raw/M-C-306_R1_001.fastq.gz ../data/raw/M-C-329_R1_001.fastq.gz ../data/raw/M-C-334_R1_001.fastq.gz ../data/raw/M-C-337_R1_001.fastq.gz ../data/raw/M-C-339_R1_001.fastq.gz ../data/raw/M-C-358_R1_001.fastq.gz ../data/raw/M-C-360_R1_001.fastq.gz ../data/raw/M-C-363_R1_001.fastq.gz ../data/raw/M-C-373_R1_001.fastq.gz ../data/raw/M-C-482_R1_001.fastq.gz ../data/raw/M-C-488_R1_001.fastq.gz ../data/raw/M-T-18_R1_001.fastq.gz ../data/raw/M-T-20_R1_001.fastq.gz ../data/raw/M-T-22_R1_001.fastq.gz ../data/raw/M-T-235_R1_001.fastq.gz ../data/raw/M-T-245_R1_001.fastq.gz ../data/raw/M-T-29_R1_001.fastq.gz ../data/raw/M-T-31_R1_001.fastq.gz ../data/raw/M-T-32_R1_001.fastq.gz ../data/raw/M-T-399_R1_001.fastq.gz ../data/raw/M-T-43_R1_001.fastq.gz ../data/raw/M-T-44_R1_001.fastq.gz ../data/raw/M-T-500_R1_001.fastq.gz ../data/raw/M-T-7_R1_001.fastq.gz ../data/raw/M-T-83_R1_001.fastq.gz ../data/raw/M-T-8_R1_001.fastq.gz
(ERR): Read file '../data/raw/*R1_001.fastq.gz' doesn't exist
Exiting now ...
